src/eureciclo_challenge/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sales/', include('sales.urls', namespace='sales'))
]

src/sales/urls.py
# pylint: disable=no-member,import-error
'''
  Sales urls.
'''
from django.urls import path
from . import views


app_name = "sales"  # pylint: disable=invalid-name

urlpatterns = [
    path("", views.SalesListView.as_view(), name="list"),
    path("<int:pk>/", views.SaleDetailView.as_view(), name="detail"),
    path("import/", views.ImportView.as_view(), name="import"),
    path(
      "import/processing/",
      views.ProcessingView.as_view(),
      name="processing"
    ),
    path("import/processing/result", views.ResultView.as_view(), name="result")
]

src/sales/models.py
# pylint: disable=no-member,import-error
'''
    Sale app models.
'''
from typing import Any, List
from django.db import models
from django.core.files.uploadedfile import UploadedFile
from errors.lib.txt_parser.invalid_file_content_exception import (
    InvalidFileContentException
)
from lib.file_handler import FileHandler
from lib.txt_parser import TxtParser


class Sale(models.Model):
    '''
        Model to represent a sale.
    '''
    buyer = models.CharField(max_length=255)
    description = models.TextField()
    price = models.FloatField()
    quantity = models.IntegerField()
    address = models.CharField(max_length=255)
    provider = models.CharField(max_length=255)

    @classmethod
    def create(cls, sale_data: dict) -> None:
        '''
            Create a sale.
        '''
        try:
            buyer = sale_data['buyer']
            description = sale_data['description']
            price = float(sale_data['price'])
            quantity = int(sale_data['quantity'])
            address = sale_data['address']
            provider = sale_data['provider']
        except KeyError:
            raise InvalidFileContentException(
                f'Dados de venda inválidos: {sale_data}'
            ) from KeyError

        cls.objects.create(
            buyer=buyer,
            description=description,
            price=price,
            quantity=quantity,
            address=address,
            provider=provider,
        )

    @property
    def total_price(self) -> float:
        '''
            Return sale's total price.
        '''
        return self.price * self.quantity

    @staticmethod
    def get_last() -> Any:
        '''
            Return the last sale.
        '''
        return Sale.objects.last()

    @staticmethod
    def get_count() -> int:
        '''
            Return the sales count.
        '''
        return Sale.objects.count()

    @staticmethod
    def get_total_price() -> float:
        '''
            Return the sales total price.
        '''
        all_sales = Sale.objects.all()

        return sum(list(map(lambda sale: sale.total_price, all_sales)))

    @staticmethod
    def compose_from_file(
        file: UploadedFile,
        file_handler: FileHandler,
        txt_parser: TxtParser
    ) -> dict:
        '''
            Compose the sales data from the uploaded file.
        '''
        file_content = file_handler.get_file_lines_content(file)

        return txt_parser.get_composed_sales(file_content)

    @staticmethod
    def create_from_list(sales_list: List[dict]) -> None:
        '''
            Create sales from a list.
        '''
        for sale in sales_list:
            Sale.create(sale)

    @staticmethod
    def get_total_imported_sales(sales: list) -> int:
        '''
            Return the number of imported sales from a file.
        '''
        return len(sales)

    @staticmethod
    def get_total_price_from_imported_sales(sales: list) -> float:
        '''
            Return the imported sales total price.
        '''
        total_price = 0.0

        for sale in sales:
            total_price += float(sale['price']) * int(sale['quantity'])

        return total_price

src/sales/views.py
# pylint: disable=no-member,import-error,unused-argument
'''
    Import views.
'''
from django.views.generic import TemplateView, ListView, DetailView
from django.shortcuts import render, redirect
from django.http import HttpResponse
from errors.lib.txt_parser.invalid_file_content_exception import (
    InvalidFileContentException
)
from errors.lib.txt_parser.invalid_line_content_exception import (
    InvalidLineContentException
)
from errors.lib.txt_parser.parse_exception import ParseException

from lib.file_handler import FileHandler
from lib.txt_parser import TxtParser
from .models import Sale


class ImportView(TemplateView):
    '''
        Import view.
    '''
    template_name = 'import.html'

    def get(self, *args, **kwargs) -> HttpResponse:
        last_sale = Sale.get_last()
        sales_count = Sale.get_count()
        sales_total_price = Sale.get_total_price()

        error = self.request.session.get('import_sales_error')

        self.request.session['import_sales_error'] = None
        self.request.session['sales_info'] = None

        data = {
            'last_sale': last_sale,
            'sales_count': sales_count,
            'sales_total_price': sales_total_price,
            'error': error
        }

        return render(self.request, 'import.html', data)


class ProcessingView(TemplateView):
    '''
        Processing sale view.
    '''
    template_name = 'processing.html'

    def post(self, *args, **kwargs) -> HttpResponse:
        '''
            Process the import sales file.
        '''
        error = ''
        file_handler = FileHandler()
        txt_parser = TxtParser()

        try:
            sales_info = Sale.compose_from_file(
                self.request.FILES['sales'],
                file_handler,
                txt_parser
            )
        except InvalidFileContentException as invalid_file_content:
            error = str(invalid_file_content)
        except InvalidLineContentException as invalid_line_content:
            error = str(invalid_line_content)
        except ParseException as parse_exception:
            error = str(parse_exception)
        except Exception as unknown_error:  # pylint: disable=broad-except
            error = f'Aconteceu um erro desconhecido: {str(unknown_error)}'  # noqa: E501

        if error:
            self.request.session['import_sales_error'] = error
            return redirect('/sales/import')

        self.request.session['sales_info'] = sales_info

        return render(self.request, 'processing.html', {'sales': sales_info})


class ResultView(TemplateView):
    '''
        Import result view.
    '''
    template_name = 'result.html'

    def get(self, *args, **kwargs) -> HttpResponse:
        '''
            Save the sales and render the results.
        '''
        sales_info = self.request.session.get('sales_info')

        if not sales_info:
            return redirect('/sales/import')

        Sale.create_from_list(sales_info)

        total_imported_sales = Sale.get_total_imported_sales(sales_info)
        total_price_from_imported_sales = Sale.get_total_price_from_imported_sales(  # noqa: E501
            sales_info
        )

        results = {
            'total_imported_sales': total_imported_sales,
            'total_price': total_price_from_imported_sales
        }

        self.request.session['sales_info'] = None

        return render(self.request, 'result.html', results)


class SalesListView(ListView):
    '''
        Sales view.
    '''
    model = Sale
    context_object_name = 'sales_list'


class SaleDetailView(DetailView):
    '''
        Sale detail view.
    '''
    model = Sale
    context_object_name = 'sale'

src/sales/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    {% block metainfo %} {% endblock %}
  </head>
  <body>
    {% include 'partials/header.html' %}
    <main>

      {% block content %} {% endblock %}

    </main>
  </body>
</html>

src/sales/templates/import.html
{% extends 'base.html' %}
{% block metainfo %}
  <title>Importar vendas</title>
{% endblock %}
{% block content %}
  <div class="container pb-6 my-6">
    <div class="is-flex is-flex-direction-column is-align-items-center">
      <h1 class="title">Adicione mais vendas</h1>
      <form action="{% url 'sales:processing' %}" method="POST" enctype="multipart/form-data" class="is-flex is-flex-direction-column is-align-items-center">
        {% csrf_token %}
        <div class="file is-centered is-boxed">
          <label class="file-label">
            <input class="file-input" type="file" name="sales" accept=".txt" required>
            <span class="file-cta">
              <span class="file-label">
                Escolha o arquivo ...
              </span>
            </span>
            <span class="file-name">
              Nenhum arquivo selecionado
            </span>
          </label>
        </div>
        <button class="button is-primary my-4" type="submit">Iniciar</button>
      </form>
      {% if error %}
        <div class="notification is-danger is-light">
          {{ error }}
        </div>
      {% endif %}
    </div>
  </div>
  <div class="level">
    <div class="level-item has-text-centered">
      <div>
        <p class="heading">Última venda</p>
        {% if last_sale %}
          <p class="title is-4">{{ last_sale.buyer }} - R$ {{ last_sale.total_price|floatformat:2 }}</p>
        {% else %}
          <p>Sem vendas cadastradas</p>
        {% endif %}
      </div>
    </div>
    <div class="level-item has-text-centered">
      <div>
        <p class="heading">Total de vendas</p>
        <p class="title">{{ sales_count }}</p>
      </div>
    </div>
    <div class="level-item has-text-centered">
      <div>
        <p class="heading">Valor total das vendas</p>
        {% if sales_total_price %}
          <p class="title">R$ {{ sales_total_price|floatformat:2 }}</p>
        {% else %}
          <p class="title">-</p>
        {% endif %}
      </div>
    </div>
  </div>
  {% load static %}
  <script src="{% static 'js/index.js' %}" defer></script>
{% endblock %}

src/sales/templates/index.html
{% extends 'base.html' %}
{% block metainfo %}
  <title>Home</title>
{% endblock %}
{% block content %}
  <div class="container pb-6 my-6">
    <div class="is-flex is-flex-direction-column is-align-items-center">
      <h1 class="title">Adicione mais vendas</h1>
      <form action="{% url 'sales:processing' %}" method="POST" enctype="multipart/form-data" class="is-flex is-flex-direction-column is-align-items-center">
        {% csrf_token %}
        <div class="file is-centered is-boxed">
          <label class="file-label">
            <input class="file-input" type="file" name="sales" accept=".txt" required>
            <span class="file-cta">
              <span class="file-label">
                Escolha o arquivo ...
              </span>
            </span>
            <span class="file-name">
              Nenhum arquivo selecionado
            </span>
          </label>
        </div>
        <button class="button is-primary my-4" type="submit">Iniciar</button>
      </form>
      {% if error %}
        <div class="notification is-danger is-light">
          {{ error }}
        </div>
      {% endif %}
    </div>
  </div>
  <div class="level">
    <div class="level-item has-text-centered">
      <div>
        <p class="heading">Última venda</p>
        {% if last_sale %}
          <p class="title">{{ last_sale.buyer }} - R$ {{ last_sale.total_price|floatformat:2 }}</p>
        {% else %}
          <p>Sem vendas cadastradas</p>
        {% endif %}
      </div>
    </div>
    <div class="level-item has-text-centered">
      <div>
        <p class="heading">Total de vendas</p>
        <p class="title">{{ sales_count }}</p>
      </div>
    </div>
    <div class="level-item has-text-centered">
      <div>
        <p class="heading">Valor total das vendas</p>
        {% if sales_total_price %}
          <p class="title">R$ {{ sales_total_price|floatformat:2 }}</p>
        {% else %}
          <p class="title">-</p>
        {% endif %}
      </div>
    </div>
  </div>
  {% load static %}
  <script src="{% static 'js/index.js' %}" defer></script>
{% endblock %}

src/sales/templates/partials/header.html
{% load static %}
<header class="container py-4">
  <div class="columns">
    <div class="column is-one-third">
      <h1 class="title has-text-primary">Vendas eureciclo</h1>
    </div>
    <div class="column is-one-third is-offset-one-third">
      <nav class="navbar-menu">
        <a class="navbar-item is-primary" href="{% url 'sales:import' %}">Importação</a>
        <a class="navbar-item is-primary" href="{% url 'sales:list' %}">Vendas</a>
      </nav>
    </div>
  </div>
</header>

src/sales/templates/processing.html
{% extends 'base.html' %}
{% block metainfo %}
  <title>Processamento</title>
{% endblock %}
{% block content %}
  <div class="container pb-6 my-6">
    <div class="pb-4">
      <h1 class="title">Vendas a importar</h1>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>Comprador</th>
          <th>Descrição</th>
          <th>Preço</th>
          <th>Quantidade</th>
          <th>Endereço</th>
          <th>Fornecedor</th>
        </tr>
      </thead>
      <tbody>
        {% for sale in sales %}
          <tr>
            <td>{{ sale.buyer }}</td>
            <td>{{ sale.description }}</td>
            <td>{{ sale.price }}</td>
            <td>{{ sale.quantity }}</td>
            <td>{{ sale.address }}</td>
            <td>{{ sale.provider }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="columns py-4">
      <div class="column is-1">
        <a class="button is-light" href="{% url 'sales:import' %}">Cancelar</a>
      </div>
      <div class="column is-1 ml-4">
        <a class="button is-success" href="{% url 'sales:result' %}">Salvar</a>
      </div>
    </div>
  </div>
{% endblock %}

src/sales/templates/result.html
{% extends 'base.html' %}
{% block metainfo %}
  <title>Resultado</title>
{% endblock %}
{% block content %}
  <div class="container pb-6 my-6">
    <div class="pb-4">
      <h1 class="title">Dados importados</h1>
    </div>
    <div class="level">
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Vendas importadas</p>
          <p class="title">{{ total_imported_sales }}</p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Receita bruta total</p>
          <p class="title">R$ {{ total_price|floatformat:2 }}</p>
        </div>
      </div>
    </div>
    <div class="is-flex is-justify-content-center py-4">
      <a class="button is-light" href="{% url 'sales:import' %}">Fechar</a>
    </div>
  </div>
{% endblock %}

src/sales/templates/sales/sale_detail.html
{% extends 'base.html' %}
{% block metainfo %}
  <title>Vendas</title>
{% endblock %}
{% block content %}
  <div class="container pb-6 my-6">
    <div class="pb-4">
      <h1 class="title">Informações da venda</h1>
    </div>
    <div class="card">
      <header class="card-header py-2 pl-4">
        <p class="title">{{ sale.buyer }}</p>
      </header>
      <div class="card-content">
        <div class="content">
          <p><strong>Endereço:</strong> {{ sale.address }}</p>
          <p><strong>Fornecedor:</strong> {{ sale.provider }}</p>
          <p><strong>Descrição:</strong> {{ sale.description }}</p>
          <p><strong>Preço (R$):</strong> {{ sale.price|floatformat:2 }}</p>
          <p><strong>Quantidade:</strong> {{ sale.quantity }}</p>
          <p><strong>Valor total (R$):</strong> {{ sale.total_price|floatformat:2 }}</p>
        </div>
      </div>
    </div>
    <div class="columns py-4">
      <div class="column is-1">
        <a class="button is-light" href="{% url 'sales:list' %}">Voltar</a>
      </div>
    </div>
  </div>
{% endblock %}

src/sales/templates/sales/sale_list.html
{% extends 'base.html' %}
{% block metainfo %}
  <title>Vendas</title>
{% endblock %}
{% block content %}
  <div class="container pb-6 my-6">
    <div class="pb-4">
      <h1 class="title">Vendas cadastradas</h1>
    </div>
    {% if sales_list %}
      <table class="table">
        <thead>
          <tr>
            <th>Comprador</th>
            <th>Descrição</th>
            <th>Preço</th>
            <th>Quantidade</th>
            <th>Endereço</th>
            <th>Fornecedor</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for sale in sales_list %}
            <tr>
              <td>{{ sale.buyer }}</td>
              <td>{{ sale.description }}</td>
              <td>R$ {{ sale.price|floatformat:2 }}</td>
              <td>{{ sale.quantity }} unidade(s)</td>
              <td>{{ sale.address }}</td>
              <td>{{ sale.provider }}</td>
              <td>
                <a class="button is-small is-primary" href="{% url 'sales:detail' sale.id %}">Ver detalhes</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <div class="py-6">
        <p>Sem vendas cadastradas</p>
      </div>
    {% endif %}
    <div class="columns py-4">
      <div class="column is-1">
        <a class="button is-light" href="{% url 'sales:import' %}">Voltar para importação</a>
      </div>
    </div>
  </div>
{% endblock %}